verse1:
  build: ./
  volumes:
    - ./:/app
  ports:
    - 8880:8880
  environment:
    - SERVER_PORT=8880
    - USE_HTTPS=0
    - HTTPS_KEY_FILE_PATH=
    - HTTPS_CERT_FILE_PATH=
    - HTTPS_SERVER_PORT=8881
  command:
    sh -c 'npm i && npm run start'